import PDFDocument from 'pdfkit';
import { Sample, TestResult, Parameter } from '@prisma/client';

export const generateReportPDF = (
  sample: Sample,
  testResults: (TestResult & { parameter: Parameter })[],
  generatedBy: string
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Header
      doc.fontSize(20).text('Water Testing Laboratory Report', { align: 'center' });
      doc.moveDown();

      // Sample Details
      doc.fontSize(12).text(`Sample Number: ${sample.sampleNumber}`);
      doc.text(`Client Name: ${sample.clientName}`);
      doc.text(`Source Location: ${sample.sourceLocation}`);
      doc.text(`Sample Type: ${sample.sampleType}`);
      doc.text(`Collection Date: ${sample.collectionDate.toDateString()}`);
      doc.moveDown();

      // Test Results Table Header
      doc.fontSize(14).text('Test Results:', { underline: true });
      doc.moveDown(0.5);

      const tableTop = doc.y;
      doc.fontSize(10);
      doc.text('Parameter', 50, tableTop);
      doc.text('Result', 200, tableTop);
      doc.text('Unit', 270, tableTop);
      doc.text('Limits', 340, tableTop);
      doc.text('Status', 450, tableTop);
      
      doc.moveTo(50, tableTop + 15).lineTo(500, tableTop + 15).stroke();

      let y = tableTop + 25;

      testResults.forEach((result) => {
        const param = result.parameter;
        const limitText = `${param.minLimit ?? 0} - ${param.maxLimit ?? '∞'}`;
        const statusText = result.isCompliant ? 'PASS' : 'FAIL';

        doc.fillColor(result.isCompliant ? 'black' : 'red');
        
        doc.text(param.name, 50, y);
        doc.text(result.measuredValue.toString(), 200, y);
        doc.text(param.unit, 270, y);
        doc.text(limitText, 340, y);
        doc.text(statusText, 450, y);

        y += 20;
      });

      doc.fillColor('black');
      doc.moveDown(2);

      // Footer
      doc.fontSize(10).text(`Generated By: ${generatedBy}`, 50, doc.y);
      doc.text(`Date: ${new Date().toLocaleString()}`, 50, doc.y);

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};
