import { Sample, TestResult, Parameter } from '@prisma/client';

export const generateReportText = (
  sample: Sample,
  testResults: (TestResult & { parameter: Parameter })[],
  generatedBy: string
): string => {
  let text = `=================================================\n`;
  text += `        WATER TESTING LABORATORY REPORT\n`;
  text += `=================================================\n\n`;

  text += `Sample Number:    ${sample.sampleNumber}\n`;
  text += `Client Name:      ${sample.clientName}\n`;
  text += `Source Location:  ${sample.sourceLocation}\n`;
  text += `Sample Type:      ${sample.sampleType}\n`;
  text += `Collection Date:  ${sample.collectionDate.toDateString()}\n\n`;
  
  text += `-------------------------------------------------\n`;
  text += `TEST RESULTS:\n`;
  text += `-------------------------------------------------\n`;
  
  // Create a simple text table
  text += `Parameter            Result     Unit       Limits        Status\n`;
  text += `-------------------------------------------------\n`;

  testResults.forEach((result) => {
    const param = result.parameter;
    const limitText = `${param.minLimit ?? 0} - ${param.maxLimit ?? '∞'}`;
    const statusText = result.isCompliant ? 'PASS' : 'FAIL';

    const paramStr = param.name.padEnd(20);
    const resultStr = result.measuredValue.toString().padEnd(10);
    const unitStr = param.unit.padEnd(10);
    const limitStr = limitText.padEnd(14);
    
    text += `${paramStr} ${resultStr} ${unitStr} ${limitStr} ${statusText}\n`;
  });

  text += `\n-------------------------------------------------\n`;
  text += `Generated By:     ${generatedBy}\n`;
  text += `Date:             ${new Date().toLocaleString()}\n`;
  text += `=================================================\n`;

  return text;
};
